### ISSUE TITLE
Re-merge this with eyalroz' repository

### ISSUE THREAD

**Issue by eyalroz** [valco1994/ssb-dbgen#3]
Hello Valentin,

I couldn't figure out your email, so I'm writing you via the issues mechanism.

I think it would be better if all (generally-applicable) improvements and fixes to the SSB dbgen happen on one repository rather than on several, to avoid fragmentation. Would you consider joining efforts in maintaining such a single repository?

As an example, I noticed your Issue #2 , that's open. This issue is supposedly relevant in my repository as well, right? Well - why not file it there,, in which case I could look at it as well.

You're welcome to email me if you like (via my profile page).

**Comment by valco1994** [comment]
Hello Eyal,

I completely agree that all generally-appliable changes should be synchronized between repositories. The problem from issue #2 has been solved a pretty long time ago, I just forgot to close the issue. And forgot to make a pull request too, probably I was in a hurry.

So, I'll create a pull request to your repo soon. And I add e-mail to profile description, so, you can use it now :)
